create table account (
	id bigint generated by default as identity,
	name varchar(64) not null,
	mobile varchar(20) not null,
	email varchar(128),
	hash_password varchar(255),
	primary key (id)
);

insert into account (id, mobile, email, name, hash_password) values(1, '11111111111', 'mingrui@352.com','MingRui','+2MunThvGcEfdYIFlT4NQQHt6z4=');
insert into account (id, mobile, email, name, hash_password) values(2, '11111111112', 'xiangyang@352.com','XiangYang','+2MunThvGcEfdYIFlT4NQQHt6z4=');
insert into account (id, mobile, email, name, hash_password) values(3, '11111111113', 'jiangjianfeng@352.com','Jason','+2MunThvGcEfdYIFlT4NQQHt6z4=');