drop table if exists account;
drop table if exists message;

create table account (
	id bigint generated by default as identity,
	name varchar(64) not null,
	mobile varchar(20) not null,
	email varchar(128),
	hash_password varchar(255),
	primary key (id)
);

create table message (
	id bigint generated by default as identity,
	receiver_id bigint null,
	message varchar(256),
	receive_date timestamp,
	primary key (id)
);